#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dynette"
name = "Dynette"

description.en = "The YunoHost DynDNS server"
description.fr = "Le serveur DynDns de Yunohost"

version = "2.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://yunohost.org"
demo = "https://dyndns.yunohost.org"

code = "https://github.com/yunohost/dynette"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"

disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.iface]
    type = "string"
    default = "eth0"
    ask.en = "The network interface on which to expose the DNS server"
    ask.fr = "L'interface réseau sur laquelle exposer le serveur DNS"

    [install.subdomains]
    type = "string"
    ask.en = "Choose subdomains managed by Dynette"
    ask.fr = "Choisissez les sous domaines gérés par Dynette"
    help.en = "A comma-separated list, can contain spaces."
    example = "nohost.me, noho.st, ynh.fr"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    dir = "/var/lib/__APP__"
    subdirs = ["db"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.exposed = false
    named.default = 1053

    [resources.apt]
    packages = [
        "python3",
        "python3-venv",
        "bind9",
        "redis",
    ]
