#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/dynette"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "$install_dir"
#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

pushd "$install_dir" > /dev/null

_update_venv
ynh_exec_as_app "$install_dir/venv/bin/pip" install -r dynette/requirements.txt > /dev/null

popd > /dev/null

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add --template="dynette-regen-named-conf.path" --destination="$dynette_regen_named_conf_path"
ynh_config_add_systemd --template="dynette-regen-named-conf.service" --service="$app-regen-named-conf"
ynh_config_add_systemd

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl  --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
