#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd
ynh_safe_rm "$dynette_regen_named_conf_path"
ynh_config_remove_systemd "$app-regen-named-conf"

ynh_safe_rm "/etc/yunohost/hooks.d/post_iptable_rules/$app-named"

ynh_config_remove_logrotate

ynh_config_remove_nginx

_rm_config_named

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
