#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

mv "/etc/bind/named.conf.options" "/etc/bind/named.conf.options.orig"
ynh_restore "/etc/bind/named.conf.options"

#=================================================
# RESTORE THE DATA DIRS
#=================================================
ynh_script_progression "Restoring the data directories..."

# Backup data directories
ynh_restore "$data_dir"
ynh_restore "/var/lib/bind"
ynh_restore "/var/cache/bind"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "$dynette_regen_named_conf_path"
ynh_restore "/etc/systemd/system/$app-regen-named-conf.service"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Dynette gunicorn daemon" --log="/var/log/$app/$app.log"

mkdir -p /etc/yunohost/hooks.d/post_iptable_rules/
ynh_restore "/etc/yunohost/hooks.d/post_iptable_rules/$app-named"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="named" --action="start"
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
