#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Stopping unconfigured named..."

ynh_systemctl --service="named" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_git_clone_or_pull "$install_dir/dynette"
chown -R "$app:$app" "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Upgrading app..."

pushd "$install_dir" > /dev/null

_update_venv
ynh_exec_as_app "$install_dir/venv/bin/pip" install -r dynette/requirements.txt > /dev/null

popd > /dev/null

ynh_config_add --template="config.yml" --destination="$install_dir/dynette/config.yml"
ynh_config_add --template="gunicorn.py" --destination="$install_dir/dynette/gunicorn.py"

#=================================================
# NAMED CONFIGURATION
#=================================================
ynh_script_progression "Upgrading named configurations..."

_add_config_named

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add --template="dynette-regen-named-conf.path" --destination="$dynette_regen_named_conf_path"

ynh_config_add_systemd --template="dynette-regen-named-conf.service" --service="$app-regen-named-conf"
ynh_config_add_systemd

yunohost service add "$app-regen-named-conf" --description="Dynette regen" --log="/var/log/$app/$app.log"
yunohost service add "$app" --description="Dynette gunicorn daemon" --log="/var/log/$app/$app.log"

mkdir -p /etc/yunohost/hooks.d/post_iptable_rules/
ynh_config_add --template="iptables.sh" --destination="/etc/yunohost/hooks.d/post_iptable_rules/$app-named"
chmod +x "/etc/yunohost/hooks.d/post_iptable_rules/$app-named"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-regen-named-conf" --action="start"
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
